# Generated by Django 4.2.5 on 2023-10-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=40)),
                ('repetirsenha', models.CharField(max_length=40)),
            ],
        ),
    ]
