# Generated by Django 4.2.3 on 2023-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('conteudo', models.TextField(max_length=50)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
    ]
