# Generated by Django 4.2.5 on 2023-09-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='mostrar',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
