# Generated by Django 4.2.5 on 2023-10-09 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postagem_imagem_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=50),
        ),
    ]
