# Generated by Django 4.2.5 on 2023-11-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('data_nasci', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Hospedes',
            },
        ),
        migrations.CreateModel(
            name='Quartos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('numero', models.IntegerField(max_length=10)),
                ('valor_diaria', models.FloatField(max_length=30)),
                ('capacidade', models.IntegerField(max_length=10)),
                ('descricao', models.TextField(max_length=150)),
                ('ativo', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quartos',
            },
        ),
    ]
