# Generated by Django 4.2.5 on 2023-11-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('entrada_prevista', models.DateField()),
                ('saida_prevista', models.DateField()),
                ('quarto_disponivel', models.CharField(max_length=40)),
                ('valor_estadia', models.FloatField(max_length=30)),
                ('numero_pessoas', models.IntegerField(max_length=10)),
                ('hospedes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.hospedes')),
                ('quartos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.quartos')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
